DEFAULT_INPUT_FASTA = "data/raw/sequence.fasta"
DEFAULT_NEXTCLADE_EXE = r"C:\Games\Nextclade\nextclade.exe"
DEFAULT_NEXTCLADE_DATASET = r"C:\Games\Nextclade\sars-cov-2"
DEFAULT_NEXTCLADE_TSV = "results/nextclade.tsv"

METADATA_SHEET = "Metadata_counts"
CDS_SHEET = "CDS_features"
SEQUENCES_SHEET = "Sequences"
QC_SUMMARY_SHEET = "QC_summary"
NEXTCLADE_SHEET = "Nextclade_results"
NEXTCLADE_QC_SHEET = "Nextclade_QC"
NEXTCLADE_MUTATIONS_SHEET = "Nextclade_Mutations"
NEXTCLADE_SUMMARY_SHEET = "Nextclade_Summary"
